/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.wildermods.workspace;

import org.gradle.api.Project;
import org.gradle.api.tasks.compile.JavaCompile;

import com.wildermods.workspace.gradle.plugin.tasks.CopyLocalDependenciesToWorkspaceTask;

import org.gradle.api.Plugin;

public class WilderWorkspacePlugin implements Plugin<Project> {
    public void apply(Project project) {
        
        project.getTasks().register("copyLocalDependenciesToWorkspace", CopyLocalDependenciesToWorkspaceTask.class, task -> {
        	
        });
        
        project.getTasks().named("compileJava", JavaCompile.class, compileJava -> {
        	compileJava.dependsOn(project.getTasks().named("copyLocalDependenciesToWorkspace"));
        });
        
        project.getTasks().withType(JavaCompile.class).configureEach(javaCompile -> {
            javaCompile.dependsOn(project.getTasks().named("copyLocalDependenciesToWorkspace"));
        });
    }
}
